name = "TestCancellation"
uuid = "ec8fdfce-d8d8-469d-87b7-ba83698e5e62"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Jive = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Sockets", "Jive"]
